import { z } from 'zod'

export const styleSchema = z.object({
  data: z.object({
    desktop_button_copy: z.object({
      copy_button_background_color: z.string(),
      copy_button_background_hover_color: z.string(),
      copy_button_background_hover_opacity: z.string(),
      copy_button_background_opacity: z.string(),
      copy_button_background_selected_color: z.string(),
      copy_button_background_selected_opacity: z.string(),
      copy_button_border_color: z.string(),
      copy_button_border_opacity: z.string(),
      copy_button_text_color: z.string(),
      copy_button_text_opacity: z.string()
    }),
    desktop_button_fastInput: z.object({
      background_color: z.string(),
      background_hover_color: z.string(),
      background_hover_opacity: z.string(),
      background_opacity: z.string(),
      border_color: z.string(),
      border_hover_color: z.string(),
      border_hover_opacity: z.string(),
      border_opacity: z.string(),
      text_color: z.string(),
      text_hover_color: z.string(),
      text_hover_opacity: z.string(),
      text_opacity: z.string()
    }),
    desktop_button_favorite: z.object({
      favorite_button_background_color: z.string(),
      favorite_button_background_hover_color: z.string(),
      favorite_button_background_hover_opacity: z.string(),
      favorite_button_background_opacity: z.string(),
      favorite_button_background_selected_color: z.string(),
      favorite_button_background_selected_opacity: z.string(),
      favorite_button_border_color: z.string(),
      favorite_button_border_opacity: z.string(),
      favorite_button_text_color: z.string(),
      favorite_button_text_opacity: z.string()
    }),
    desktop_button_login: z.object({
      login_button_background_color: z.string(),
      login_button_background_hover_color: z.string(),
      login_button_background_hover_opacity: z.string(),
      login_button_background_opacity: z.string(),
      login_button_background_selected_color: z.string(),
      login_button_background_selected_opacity: z.string(),
      login_button_border_color: z.string(),
      login_button_border_opacity: z.string(),
      login_button_image_large: z.string(),
      login_button_image_small: z.string(),
      login_button_image_xs: z.string(),
      login_button_text_color: z.string(),
      login_button_text_opacity: z.string(),
      style_options: z.enum(['color', 'image'])
    }),
    desktop_button_logout: z.object({
      logout_button_background_color: z.string(),
      logout_button_background_hover_color: z.string(),
      logout_button_background_hover_opacity: z.string(),
      logout_button_background_opacity: z.string(),
      logout_button_background_selected_color: z.string(),
      logout_button_background_selected_opacity: z.string(),
      logout_button_border_color: z.string(),
      logout_button_border_opacity: z.string(),
      logout_button_image: z.string(),
      logout_button_text_color: z.string(),
      logout_button_text_opacity: z.string(),
      style_options: z.enum(['color', 'image'])
    }),
    desktop_button_playNow: z.object({
      playNow_button_background_color: z.string(),
      playNow_button_background_hover_color: z.string(),
      playNow_button_background_hover_opacity: z.string(),
      playNow_button_background_opacity: z.string(),
      playNow_button_background_selected_color: z.string(),
      playNow_button_background_selected_opacity: z.string(),
      playNow_button_border_color: z.string(),
      playNow_button_border_opacity: z.string(),
      playNow_button_text_color: z.string(),
      playNow_button_text_opacity: z.string()
    }),
    desktop_button_register: z.object({
      register_button_background_color: z.string(),
      register_button_background_hover_color: z.string(),
      register_button_background_hover_opacity: z.string(),
      register_button_background_opacity: z.string(),
      register_button_background_selected_color: z.string(),
      register_button_background_selected_opacity: z.string(),
      register_button_border_color: z.string(),
      register_button_border_opacity: z.string(),
      register_button_image_large: z.string(),
      register_button_image_small: z.string(),
      register_button_image_xs: z.string(),
      register_button_text_color: z.string(),
      register_button_text_opacity: z.string(),
      style_options: z.enum(['color', 'image'])
    }),
    desktop_button_reset: z.object({
      reset_button_background_color: z.string(),
      reset_button_background_hover_color: z.string(),
      reset_button_background_hover_opacity: z.string(),
      reset_button_background_opacity: z.string(),
      reset_button_background_selected_color: z.string(),
      reset_button_background_selected_opacity: z.string(),
      reset_button_border_color: z.string(),
      reset_button_border_opacity: z.string(),
      reset_button_text_color: z.string(),
      reset_button_text_opacity: z.string()
    }),
    desktop_button_save: z.object({
      save_button_background_color: z.string(),
      save_button_background_hover_color: z.string(),
      save_button_background_hover_opacity: z.string(),
      save_button_background_opacity: z.string(),
      save_button_background_selected_color: z.string(),
      save_button_background_selected_opacity: z.string(),
      save_button_border_color: z.string(),
      save_button_border_opacity: z.string(),
      save_button_image: z.string(),
      save_button_text_color: z.string(),
      save_button_text_opacity: z.string(),
      style_options: z.enum(['color', 'image'])
    }),
    desktop_button_search: z.object({
      search_button_background_color: z.string(),
      search_button_background_hover_color: z.string(),
      search_button_background_hover_opacity: z.string(),
      search_button_background_opacity: z.string(),
      search_button_background_selected_color: z.string(),
      search_button_background_selected_opacity: z.string(),
      search_button_border_color: z.string(),
      search_button_border_opacity: z.string(),
      search_button_text_color: z.string(),
      search_button_text_opacity: z.string()
    }),
    desktop_button_seeAll: z.object({
      seeAll_button_background_color: z.string(),
      seeAll_button_background_hover_color: z.string(),
      seeAll_button_background_hover_opacity: z.string(),
      seeAll_button_background_opacity: z.string(),
      seeAll_button_background_selected_color: z.string(),
      seeAll_button_background_selected_opacity: z.string(),
      seeAll_button_border_color: z.string(),
      seeAll_button_border_opacity: z.string(),
      seeAll_button_text_color: z.string(),
      seeAll_button_text_opacity: z.string()
    }),
    desktop_button_seeDetail: z.object({
      seeDetail_button_background_color: z.string(),
      seeDetail_button_background_hover_color: z.string(),
      seeDetail_button_background_hover_opacity: z.string(),
      seeDetail_button_background_opacity: z.string(),
      seeDetail_button_background_selected_color: z.string(),
      seeDetail_button_background_selected_opacity: z.string(),
      seeDetail_button_border_color: z.string(),
      seeDetail_button_border_opacity: z.string(),
      seeDetail_button_text_color: z.string(),
      seeDetail_button_text_opacity: z.string()
    }),
    desktop_button_send: z.object({
      send_button_background_color: z.string(),
      send_button_background_hover_color: z.string(),
      send_button_background_hover_opacity: z.string(),
      send_button_background_opacity: z.string(),
      send_button_background_selected_color: z.string(),
      send_button_background_selected_opacity: z.string(),
      send_button_border_color: z.string(),
      send_button_border_opacity: z.string(),
      send_button_image: z.string(),
      send_button_text_color: z.string(),
      send_button_text_opacity: z.string(),
      style_options: z.enum(['color', 'image'])
    }),
    desktop_button_swap: z.object({
      swap_button_background_color: z.string(),
      swap_button_background_hover_color: z.string(),
      swap_button_background_hover_opacity: z.string(),
      swap_button_background_opacity: z.string(),
      swap_button_border_color: z.string(),
      swap_button_border_opacity: z.string(),
      swap_button_icon_color: z.string(),
      swap_button_icon_opacity: z.string()
    }),
    desktop_button_textLink: z.object({
      textLink_color: z.string(),
      textLink_hover_color: z.string(),
      textLink_hover_opacity: z.string(),
      textLink_opacity: z.string()
    }),
    desktop_button_top: z.object({
      top_button_background_color: z.string(),
      top_button_background_hover_color: z.string(),
      top_button_background_hover_opacity: z.string(),
      top_button_background_opacity: z.string(),
      top_button_background_selected_color: z.string(),
      top_button_background_selected_opacity: z.string(),
      top_button_border_color: z.string(),
      top_button_border_opacity: z.string(),
      top_button_text_color: z.string(),
      top_button_text_opacity: z.string()
    }),
    desktop_button_verify: z.object({
      style_options: z.enum(['color', 'image']),
      verify_button_background_color: z.string(),
      verify_button_background_hover_color: z.string(),
      verify_button_background_hover_opacity: z.string(),
      verify_button_background_opacity: z.string(),
      verify_button_background_selected_color: z.string(),
      verify_button_background_selected_opacity: z.string(),
      verify_button_border_color: z.string(),
      verify_button_border_opacity: z.string(),
      verify_button_image: z.string(),
      verify_button_text_color: z.string(),
      verify_button_text_opacity: z.string()
    }),
    desktop_homepage_aboutUs: z.object({
      aboutUs_background_border_color: z.string(),
      aboutUs_background_border_opacity: z.string(),
      aboutUs_background_color: z.string(),
      aboutUs_background_opacity: z.string(),
      aboutUs_title_text_color: z.string(),
      aboutUs_title_text_opacity: z.string()
    }),
    desktop_homepage_announcement: z.object({
      background_color: z.string(),
      background_opacity: z.string(),
      contact_us_color: z.string(),
      contact_us_hover_color: z.string(),
      icon_color: z.string(),
      icon_opacity: z.string(),
      language_color: z.string(),
      language_hover_color: z.string(),
      text_color: z.string()
    }),
    desktop_homepage_body: z.object({ background_body_image: z.string() }),
    desktop_homepage_carousel: z.object({
      carousel_indicator_color: z.string(),
      carousel_selected_indicator_color: z.string(),
      left_right_button_color: z.string(),
      left_right_button_hover_color: z.string(),
      left_right_button_hover_opacity: z.string(),
      left_right_button_opacity: z.string(),
      left_right_icon_color: z.string(),
      left_right_icon_hover_color: z.string(),
      left_right_icon_hover_opacity: z.string(),
      left_right_icon_opacity: z.string()
    }),
    desktop_homepage_favoriteGame: z.object({
      favorite_game_background_border_color: z.string(),
      favorite_game_background_border_opacity: z.string(),
      favorite_game_background_color: z.string(),
      favorite_game_background_opacity: z.string(),
      favorite_game_title_text_color: z.string(),
      favorite_game_title_text_opacity: z.string(),
      game_name_color: z.string(),
      game_name_opacity: z.string(),
      provider_name_color: z.string(),
      provider_name_opacity: z.string()
    }),
    desktop_homepage_footer: z.object({
      footer_background_border_color: z.string(),
      footer_background_border_opacity: z.string(),
      footer_background_color: z.string(),
      footer_background_opacity: z.string(),
      footer_copyright_text_color: z.string(),
      footer_copyright_text_opacity: z.string(),
      footer_text_color: z.string(),
      footer_text_opacity: z.string(),
      social_media_icon_color: z.string(),
      social_media_icon_opacity: z.string()
    }),
    desktop_homepage_gameCategoryContent: z.object({
      category_dropdown_border_color: z.string(),
      category_dropdown_border_opacity: z.string(),
      category_dropdown_color: z.string(),
      category_dropdown_opacity: z.string(),
      category_list_background_border_color: z.string(),
      category_list_background_border_opacity: z.string(),
      category_list_background_color: z.string(),
      category_list_background_image: z.string(),
      category_list_background_opacity: z.string(),
      category_list_icon_color: z.string(),
      category_list_icon_hover_color: z.string(),
      category_list_icon_hover_opacity: z.string(),
      category_list_icon_opacity: z.string(),
      category_list_icon_selected_box_color: z.string(),
      category_list_icon_selected_box_opacity: z.string(),
      play_now_button_color: z.string(),
      play_now_button_opacity: z.string(),
      play_now_button_text_color: z.string(),
      play_now_button_text_opacity: z.string(),
      provider_box_border_color: z.string(),
      provider_box_border_opacity: z.string(),
      style_options: z.enum(['color', 'image'])
    }),
    desktop_homepage_gameProvider: z.object({
      provider_background_color: z.string(),
      provider_background_opacity: z.string(),
      provider_border_color: z.string(),
      provider_border_opacity: z.string(),
      provider_box_opacity: z.string(),
      provider_list_border_color: z.string(),
      provider_list_border_opacity: z.string(),
      provider_list_color: z.string(),
      provider_list_opacity: z.string(),
      provider_title_text_color: z.string(),
      provider_title_text_opacity: z.string()
    }),
    desktop_homepage_header: z.object({
      background_color: z.string(),
      background_image: z.string(),
      background_opacity: z.string(),
      burger_button_color: z.string(),
      burger_button_hover_color: z.string(),
      coin_box_body_color: z.string(),
      coin_text_color: z.string(),
      inbox_icon_color: z.string(),
      inbox_icon_hover_color: z.string(),
      inbox_icon_selected_color: z.string(),
      profile_icon_text_color: z.string(),
      profile_icon_text_hover_color: z.string(),
      profile_icon_text_selected_color: z.string(),
      refresh_icon_color: z.string(),
      refresh_icon_hover_color: z.string(),
      style_options: z.enum(['color', 'image']),
      visibility_icon_color: z.string(),
      visibility_icon_hover_color: z.string()
    }),
    desktop_homepage_headerMainBox: z.object({
      background_color: z.string(),
      background_image: z.string(),
      background_opacity: z.string(),
      deposit_button_color: z.string(),
      deposit_button_hover_color: z.string(),
      deposit_button_hover_opacity: z.string(),
      deposit_button_image: z.string(),
      deposit_button_opacity: z.string(),
      deposit_button_selected_color: z.string(),
      deposit_button_selected_opacity: z.string(),
      deposit_style_options: z.enum(['color', 'image']),
      deposit_text_color: z.string(),
      deposit_text_opacity: z.string(),
      divider_line_color: z.string(),
      divider_line_opacity: z.string(),
      seamless_option_text_color: z.string(),
      seamless_option_text_opacity: z.string(),
      style_options: z.enum(['color', 'image']),
      transfer_button_color: z.string(),
      transfer_button_hover_color: z.string(),
      transfer_button_hover_opacity: z.string(),
      transfer_button_image: z.string(),
      transfer_button_opacity: z.string(),
      transfer_button_selected_color: z.string(),
      transfer_button_selected_opacity: z.string(),
      transfer_style_options: z.enum(['color', 'image']),
      transfer_text_color: z.string(),
      transfer_text_opacity: z.string(),
      withdraw_button_color: z.string(),
      withdraw_button_hover_color: z.string(),
      withdraw_button_hover_opacity: z.string(),
      withdraw_button_image: z.string(),
      withdraw_button_opacity: z.string(),
      withdraw_button_selected_color: z.string(),
      withdraw_button_selected_opacity: z.string(),
      withdraw_coin_button_color: z.string(),
      withdraw_coin_button_hover_color: z.string(),
      withdraw_coin_button_hover_opacity: z.string(),
      withdraw_coin_button_image: z.string(),
      withdraw_coin_button_opacity: z.string(),
      withdraw_coin_button_selected_color: z.string(),
      withdraw_coin_button_selected_opacity: z.string(),
      withdraw_coin_style_options: z.enum(['color', 'image']),
      withdraw_coin_text_color: z.string(),
      withdraw_coin_text_opacity: z.string(),
      withdraw_style_options: z.enum(['color', 'image']),
      withdraw_text_color: z.string(),
      withdraw_text_opacity: z.string()
    }),
    desktop_homepage_information: z.object({
      information_background_color: z.string(),
      information_background_opacity: z.string(),
      information_border_color: z.string(),
      information_border_opacity: z.string(),
      information_content_text_color: z.string(),
      information_content_text_opacity: z.string(),
      information_text_color: z.string(),
      information_text_opacity: z.string()
    }),
    desktop_homepage_lastPlayed: z.object({
      game_name_color: z.string(),
      game_name_opacity: z.string(),
      last_played_background_border_color: z.string(),
      last_played_background_border_opacity: z.string(),
      last_played_background_color: z.string(),
      last_played_background_opacity: z.string(),
      last_played_title_text_color: z.string(),
      last_played_title_text_opacity: z.string(),
      provider_name_color: z.string(),
      provider_name_opacity: z.string()
    }),
    desktop_homepage_paymentMethod: z.object({
      payment_method_background_color: z.string(),
      payment_method_background_opacity: z.string(),
      payment_method_border_color: z.string(),
      payment_method_border_opacity: z.string(),
      payment_method_text_color: z.string(),
      payment_method_text_opacity: z.string()
    }),
    desktop_homepage_progressiveJackpot: z.object({
      jackpot_background_color: z.string(),
      jackpot_background_image: z.string(),
      jackpot_background_opacity: z.string(),
      jackpot_border_color: z.string(),
      jackpot_border_opacity: z.string(),
      jackpot_image: z.string(),
      jackpot_text_color: z.string(),
      style_options: z.enum(['color', 'image']),
      toggle_progressive_jackpot: z.string()
    }),
    desktop_homepage_promotion: z.object({
      promotion_background_color: z.string(),
      promotion_background_opacity: z.string(),
      promotion_box_border_color: z.string(),
      promotion_box_border_opacity: z.string(),
      promotion_currency_background_color: z.string(),
      promotion_currency_background_opacity: z.string(),
      promotion_currency_border_color: z.string(),
      promotion_currency_border_opacity: z.string(),
      promotion_currency_text_color: z.string(),
      promotion_currency_text_opacity: z.string(),
      promotion_section_background_color: z.string(),
      promotion_section_background_opacity: z.string(),
      promotion_section_countdown_color: z.string(),
      promotion_section_countdown_opacity: z.string(),
      promotion_section_text_color: z.string(),
      promotion_section_text_opacity: z.string(),
      promotion_title_text_color: z.string(),
      promotion_title_text_opacity: z.string()
    }),
    desktop_otherpage_bankAccountDetail: z.object({
      background_color: z.string(),
      background_opacity: z.string(),
      border_color: z.string(),
      border_opacity: z.string(),
      name_text_color: z.string(),
      number_text_color: z.string()
    }),
    desktop_otherpage_bankDetail: z.object({
      background_color: z.string(),
      background_opacity: z.string(),
      border_color: z.string(),
      border_opacity: z.string(),
      content_text_color: z.string(),
      title_text_color: z.string()
    }),
    desktop_otherpage_coinBalance: z.object({
      background_color: z.string(),
      background_opacity: z.string(),
      border_color: z.string(),
      border_opacity: z.string(),
      content_text_color: z.string(),
      number_text_color: z.string(),
      title_text_color: z.string()
    }),
    desktop_otherpage_general: z.object({
      content_text_color: z.string(),
      content_text_opacity: z.string(),
      title_text_color: z.string(),
      title_text_opacity: z.string(),
      wrapper_background_color: z.string(),
      wrapper_background_opacity: z.string(),
      wrapper_border_color: z.string(),
      wrapper_border_opacity: z.string()
    }),
    desktop_otherpage_history: z.object({
      content_background_color: z.string(),
      content_background_opacity: z.string(),
      content_border_color: z.string(),
      content_border_opacity: z.string(),
      content_hover_background_color: z.string(),
      content_hover_background_opacity: z.string(),
      content_text_color: z.string(),
      pagination_default_text_color: z.string(),
      pagination_hover_text_color: z.string(),
      pagination_hover_text_opacity: z.string(),
      pagination_selected_background_color: z.string(),
      pagination_selected_background_opacity: z.string(),
      pagination_selected_text_color: z.string(),
      title_background_color: z.string(),
      title_background_opacity: z.string(),
      title_border_color: z.string(),
      title_border_opacity: z.string(),
      title_text_color: z.string()
    }),
    desktop_otherpage_informationBox: z.object({
      information_border_color: z.string(),
      information_border_opacity: z.string(),
      information_box_background_color: z.string(),
      information_box_background_opacity: z.string(),
      information_icon_color: z.string(),
      information_text_color: z.string()
    }),
    desktop_otherpage_playerWalletInfo: z.object({
      main_wallet_box_background_color: z.string(),
      main_wallet_box_background_opacity: z.string(),
      main_wallet_text_color: z.string(),
      wallet_line_row_color: z.string(),
      wallet_text_color: z.string(),
      wallet_title_color: z.string(),
      wallet_wrapper_background_color: z.string(),
      wallet_wrapper_background_opacity: z.string()
    }),
    desktop_otherpage_providerList: z.object({
      active_button_border_color: z.string(),
      active_button_border_opacity: z.string(),
      active_button_color: z.string(),
      active_button_opacity: z.string(),
      active_text_color: z.string(),
      default_button_border_color: z.string(),
      default_button_border_opacity: z.string(),
      default_button_color: z.string(),
      default_button_opacity: z.string(),
      default_text_color: z.string(),
      divider_line_color: z.string(),
      divider_line_opacity: z.string(),
      hover_button_border_color: z.string(),
      hover_button_border_opacity: z.string(),
      hover_button_color: z.string(),
      hover_button_opacity: z.string(),
      hover_button_shadow_color: z.string(),
      hover_button_shadow_opacity: z.string(),
      hover_text_color: z.string(),
      showHide_text_color: z.string(),
      showHide_text_opacity: z.string(),
      wrapper_background_color: z.string(),
      wrapper_background_opacity: z.string()
    }),
    desktop_otherpage_referral: z.object({
      code_background_color: z.string(),
      code_background_opacity: z.string(),
      code_border_color: z.string(),
      code_border_opacity: z.string(),
      code_icon_color: z.string(),
      code_text_color: z.string(),
      data_background_color: z.string(),
      data_background_opacity: z.string(),
      data_border_color: z.string(),
      data_border_opacity: z.string(),
      data_divider_color: z.string(),
      data_text_color: z.string(),
      link_background_color: z.string(),
      link_background_opacity: z.string(),
      link_border_color: z.string(),
      link_border_opacity: z.string(),
      link_icon_color: z.string(),
      link_text_color: z.string()
    }),
    desktop_otherpage_rtpInfo: z.object({
      rtp_background_color: z.string(),
      rtp_background_opacity: z.string(),
      rtp_text_color: z.string(),
      rtp_text_opacity: z.string()
    }),
    desktop_otherpage_sidebarMenu: z.object({
      active_icon_text_color: z.string(),
      active_line_color: z.string(),
      active_line_opacity: z.string(),
      active_tab_color: z.string(),
      active_tab_opacity: z.string(),
      default_icon_text_color: z.string(),
      default_tab_wrapper_background_color: z.string(),
      default_tab_wrapper_background_opacity: z.string(),
      hover_icon_text_color: z.string(),
      hover_tab_color: z.string(),
      hover_tab_opacity: z.string()
    }),
    desktop_otherpage_tab1: z.object({
      active_tab_line_color: z.string(),
      active_text_color: z.string(),
      default_tab_line_color: z.string(),
      default_text_color: z.string()
    }),
    desktop_otherpage_tab2: z.object({
      active_icon_text_color: z.string(),
      active_line_color: z.string(),
      active_line_opacity: z.string(),
      active_tab_color: z.string(),
      active_tab_opacity: z.string(),
      default_icon_text_color: z.string(),
      default_tab_wrapper_background_color: z.string(),
      default_tab_wrapper_background_opacity: z.string(),
      hover_icon_text_color: z.string(),
      hover_tab_color: z.string(),
      hover_tab_opacity: z.string()
    }),
    desktop_otherpage_targetTurnover: z.object({
      progress_background_color: z.string(),
      progress_border_color: z.string(),
      progress_border_opacity: z.string(),
      progress_color: z.string(),
      progress_text_color: z.string(),
      progress_text_opacity: z.string(),
      targetTurnover_box: z.string(),
      targetTurnover_text: z.string(),
      toggle_targetTurnover: z.string()
    }),
    desktop_popup_playerWalletInfo: z.object({
      wallet_popup_background_color: z.string(),
      wallet_popup_background_opacity: z.string(),
      wallet_popup_content_text_color: z.string(),
      wallet_popup_line_row_color: z.string(),
      wallet_popup_title_text_color: z.string(),
      withdraw_coin_all_button_background_color: z.string(),
      withdraw_coin_all_button_background_image: z.string(),
      withdraw_coin_all_button_background_opacity: z.string(),
      withdraw_coin_all_button_text_color: z.string(),
      withdraw_coin_small_button_color: z.string(),
      withdraw_coin_small_button_opacity: z.string(),
      withdraw_coin_style_options: z.enum(['color', 'image'])
    }),
    desktop_popup_popupBanner: z.object({
      content_popup_banner_background_color: z.string(),
      content_popup_banner_background_opacity: z.string(),
      head_popup_banner_background_color: z.string(),
      head_popup_banner_background_opacity: z.string(),
      head_popup_close_button_background_color: z.string(),
      head_popup_close_button_background_opacity: z.string(),
      head_popup_close_button_icon_color: z.string()
    }),
    desktop_popup_termsCondition: z.object({
      terms_condition_background_color: z.string(),
      terms_condition_close_button_color: z.string(),
      terms_condition_text_color: z.string()
    }),
    desktop_sidebar_menu: z.object({
      background_color: z.string(),
      background_image: z.string(),
      background_opacity: z.string(),
      icon_color: z.string(),
      icon_opacity: z.string(),
      menu_hover_color: z.string(),
      menu_hover_opacity: z.string(),
      section_title_color: z.string(),
      section_title_opacity: z.string(),
      style_options: z.enum(['color', 'image']),
      text_color: z.string(),
      text_opacity: z.string()
    })
  })
})

export type TStyle = z.infer<typeof styleSchema>['data']
export type TStyleResponse = z.infer<typeof styleSchema>
